version: "3"

services:
  app:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    ports:
      - 185.255.90.121:7852:80
    environment:
      - TZ='Africa/Casablanca'
    volumes:
      - ./data:/app/data
